name: Access DigitalOcean Server

on:
  push:
    branches:
      - main

jobs:
  access-digitalocean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add DigitalOcean to Known Hosts
        run: |
          ssh-keyscan -H <YOUR_DIGITALOCEAN_SERVER_IP> >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh root@<YOUR_DIGITALOCEAN_SERVER_IP> "echo Connected to DigitalOcean"
